books = {
  { title = "The Quiet Inventory", author = "Samuel K. Doyle", synopsis = "An office clerk catalogs forgotten objects and notices patterns that mirror civic choices.", censored = true },
  { title = "Baking on Sundays", author = "Helen Moore", synopsis = "A small-town baker records recipes and the gentle rhythms of morning trade.", censored = false },
  { title = "The Map Between Streets", author = "Arthur Bell", synopsis = "A delivery driver redraws the city from memory and reflects on paths people avoid.", censored = true },
  { title = "Notes on Weather", author = "Clara Whitman", synopsis = "A personal journal describes clouds and small mood shifts over a single season.", censored = false },
  { title = "Instructions for Assembly", author = "Leonard Price", synopsis = "A factory manual becomes a slow essay on repetition and who is visible in labor.", censored = true },
  { title = "Salted Windows", author = "Maya Khan", synopsis = "A seaside washer documents panes and the brief conversations of harbor workers.", censored = false },
  { title = "Ledger of Missed Meetings", author = "Jon Reed", synopsis = "A municipal ledger lists appointments that were canceled and hints at unspoken priorities.", censored = true },
  { title = "Herbal Evenings", author = "Irene Marin", synopsis = "A gardener writes short notes on herbs and the neighbors who borrow them.", censored = false },
  { title = "Margins of a City", author = "Victor Lopez", synopsis = "A scholar collects marginal notes from public reports and sees a hidden logic of care.", censored = true },
  { title = "Sunday Repairs", author = "Lena Hart", synopsis = "A repairman journals small fixes and the gratitude exchanged over coffee.", censored = false },
  { title = "Catalogue of Quiet Acts", author = "Gideon Gold", synopsis = "An archivist indexes anonymous deeds that, together, suggest an alternate public memory.", censored = true },
  { title = "Evening Bread", author = "Nora Fisher", synopsis = "A baker recalls conversations at closing time and the little favors traded in town.", censored = false },
  { title = "Paper Streets", author = "Paul Cole", synopsis = "A cartographer finds erased lanes on old maps and wonders who rewrote routes for convenience.", censored = true },
  { title = "The Clock Repair", author = "Ruth Bennett", synopsis = "A clockmaker notes rhythms of a neighborhood and how time feels to different people.", censored = false },
  { title = "Register of Small Debts", author = "Omar Diaz", synopsis = "A ledge of IOUs uncovers networks of obligation that challenge official accounts.", censored = true },
  { title = "Pondside Recipes", author = "Doris Harper", synopsis = "A list of simple recipes shared by a tight-knit community across summers.", censored = false },
  { title = "The Fifth Notice", author = "Miles Stone", synopsis = "A discarded notice reveals patterns of warning and who receives them first.", censored = true },
  { title = "Lanterns at Dusk", author = "Fiona Ward", synopsis = "A poet writes brief scenes of lantern-lit walks and neighbors exchanging stories.", censored = false },
  { title = "Inventory of Giving", author = "Hank Brooks", synopsis = "An informal inventory records what people give away and what that implies about need.", censored = true },
  { title = "Notes from the Ferry", author = "Sofia Gray", synopsis = "A ferry worker jotting small observations about passengers and their silent rituals.", censored = false },
  { title = "The Hidden Key", author = "E. Harrow", synopsis = "A clerk finds a key index that links minor places to acts of conscience.", censored = true },
  { title = "Midsummer Mending", author = "Celia Ruiz", synopsis = "Neighbors gather to mend clothes while swapping stories of small daily kindnesses.", censored = false },
  { title = "Procedure for Quiet Change", author = "Noah Finch", synopsis = "A procedural manual, when read end to end, suggests subtle ways to alter expectations.", censored = true },
  { title = "Paper Boats", author = "Ivy Tan", synopsis = "Children fold paper boats and race them in gutters, shouting names aloud.", censored = false },
  { title = "The Index of Lost Voices", author = "Owen Carlisle", synopsis = "An index lists speakers who were ignored and maps where attention was withdrawn.", censored = true },
  { title = "Afternoon Tea Notes", author = "Rosa Bellamy", synopsis = "A collection of short reminiscences shared over steady cups of tea.", censored = false },
  { title = "Blueprints of Courtesy", author = "Trevor Hale", synopsis = "Old blueprints annotated with marginalia reveal unspoken rules of access.", censored = true },
  { title = "The Little Almanac", author = "June Park", synopsis = "A pocket almanac for gardeners with planting dates and small aphorisms.", censored = false },
  { title = "The Quiet Census", author = "Emil Novak", synopsis = "A private census records details that contradict the public figures and prompts questions.", censored = true },
  { title = "Sunday Sketches", author = "Lola Mendes", synopsis = "Two pages of sketches capturing faces at the market and passing gestures.", censored = false },
  { title = "A Manual for Small Resistances", author = "Hector Li", synopsis = "Step-by-step notes on tiny refusals that, in aggregate, change how systems behave.", censored = true },
  { title = "The Corner Florist", author = "Mina Ortiz", synopsis = "A florist notes which flowers are left behind and the brief hopes they represent.", censored = false },
  { title = "Catalog of Doors", author = "Felix Grant", synopsis = "A cataloging of doorways and who feels welcome to use them over time.", censored = true },
  { title = "Afternoon Walks", author = "Polly Grant", synopsis = "A short guide to pleasant routes and where to sit for a quiet hour.", censored = false },
  { title = "Minutes from the Back Room", author = "Rafael Costa", synopsis = "Minutes briefly mention decisions that quietly reshape neighborhood services.", censored = true },
  { title = "Sunroom Patterns", author = "Ellen Price", synopsis = "A description of patched quilts and the stories stitched into them.", censored = false },
  { title = "A Catalogue of Small Privileges", author = "Marcus Vale", synopsis = "A list of everyday privileges reveals how access is rationed across different streets.", censored = true },
  { title = "The Recipe Index", author = "Tara Singh", synopsis = "A homebound recipe book with marginal notes about guests and their tastes.", censored = false },
  { title = "Annotations on the Ledger", author = "Gwen Morris", synopsis = "Annotations expose who remains invisible in formal accounting and why it matters.", censored = true },
  { title = "The Baker's Margin", author = "Hiram Cole", synopsis = "A baker's margin notes recall favors done in exchange for silence and smiles.", censored = false },
  { title = "Routes Not Taken", author = "Silas Reed", synopsis = "A commuter's notes detail which stops are avoided and which communities are bypassed.", censored = true },
  { title = "Winter Candles", author = "Ada Browne", synopsis = "A short collection of winter memories and the candles set at window sills.", censored = false },
  { title = "The Caretaker's Register", author = "Vera Santos", synopsis = "A caretaker writes a register that highlights maintenance choices and neglected corners.", censored = true },
  { title = "Pocket Poems", author = "Luca Moretti", synopsis = "Tiny poems about rain on umbrellas and the rhythm of city commutes.", censored = false },
  { title = "The Handbook of Small Delays", author = "Celeste Young", synopsis = "A handbook noting how delay is used to prioritize some requests over others.", censored = true },
  { title = "The Window Sill", author = "Marco Bell", synopsis = "Observations of plants kept on window sills and who tends them daily.", censored = false },
  { title = "Record of Unclaimed Things", author = "Iris Hale", synopsis = "A record of abandoned items that slowly reveals patterns of inequality.", censored = true },
  { title = "Laundry Day Notes", author = "Tomiko Sato", synopsis = "A neighbor writes about washing days and the small exchanges that occur at the line.", censored = false },
  { title = "Brief on Public Quiet", author = "Conrad Pike", synopsis = "A brief that reads like civic advice, nudging how public attention might be redirected.", censored = true },
  { title = "The Sunday Quilt", author = "Naomi Ortiz", synopsis = "A quilt pattern passed down with annotations naming women who stitched it together.", censored = false },
  { title = "Ledger of Open Windows", author = "Arman Qureshi", synopsis = "An index of open windows documents who tolerates noise and who must remain silent.", censored = true },
  { title = "Market Prices and Stories", author = "Rina Patel", synopsis = "A market seller lists prices alongside short stories about regulars.", censored = false },
  { title = "Guidelines for Silent Meetings", author = "Harold Kim", synopsis = "A short guide that, when followed, systematically excludes certain voices from meetings.", censored = true },
  { title = "The Little Music Book", author = "Sasha Ivanov", synopsis = "A compact collection of simple melodies learned from neighbors and distant radios.", censored = false },
  { title = "Notes on Shared Tools", author = "Dante Ruiz", synopsis = "A register of shared tools reveals who borrows and who cannot gain access.", censored = true },
  { title = "Evening Chores", author = "Marta Leone", synopsis = "Quick entries about chores completed before dinner and the small comforts that follow.", censored = false },
  { title = "The Silent Distribution", author = "Priya Shah", synopsis = "A distribution list shows how scarce resources are quietly redirected to favored groups.", censored = true },
  { title = "A Handful of Letters", author = "Jonas Reed", synopsis = "A sequence of brief letters exchanged between neighbors over a summer.", censored = false },
  { title = "The Guide to Folding Maps", author = "Nadia Petrova", synopsis = "A folding manual that hides an alternative map for finding community gatherings.", censored = true },
  { title = "Porch Conversations", author = "Eli Navarro", synopsis = "Short dialogues overheard on porches that capture the town's small humor.", censored = false },
  { title = "An Index of Silences", author = "Ruth Klein", synopsis = "An index catalogs silences at meetings and where questions were left unanswered.", censored = true },
  { title = "The Guide to Simple Repairs", author = "Hugo Martins", synopsis = "A straightforward guide to mending everyday items for household independence.", censored = false },
  { title = "Notes from the Welfare Line", author = "Asha Menon", synopsis = "A set of notes that highlights patterns in who receives assistance and who is turned away.", censored = true },
  { title = "Tea Tins and Postcards", author = "Lorenz Weber", synopsis = "A keeper of tins and postcards records small histories of travel and return.", censored = false },
  { title = "A Short Manual on Obedience", author = "Helga Braun", synopsis = "A manual reads like instruction but prompts readers to consider why obedience is expected.", censored = true },
  { title = "Lantern Maintenance", author = "Derek Shaw", synopsis = "Brief instructions for caring for lanterns in communal spaces and passing them on.", censored = false },
  { title = "The Neighborhood Ledger", author = "Marta Silva", synopsis = "A ledger that marks patterns of maintenance spending and who benefits most.", censored = true },
  { title = "Stitching Notes", author = "Pilar Gomez", synopsis = "A seamstress lists stitches and small stories traded during long afternoons.", censored = false },
  { title = "Postmarked Choices", author = "Alexei Morozov", synopsis = "A set of postmarks ties correspondence to decision points that change access to services.", censored = true },
  { title = "Window Gardens", author = "Samiya Rahman", synopsis = "Simple notes about balcony plants and the rituals of tending them at dawn.", censored = false },
  { title = "The Handbook of Redirects", author = "Connie Park", synopsis = "A handbook describing bureaucratic redirects that systematically alter who gets help.", censored = true },
  { title = "Afternoon Calls", author = "Garry Finch", synopsis = "A short log of calls and the small favors arranged between friends.", censored = false },
  { title = "The Index of Forgotten Names", author = "Lars Engstrom", synopsis = "An index resurrects names omitted from official records and asks why they were lost.", censored = true },
  { title = "The Small Lamp", author = "Mandy Chou", synopsis = "A brief note on a lamp kept at a kitchen table and the conversations it warmed.", censored = false },
  { title = "Instructions in Minor Rebellion", author = "Pablo Rios", synopsis = "A pocket guide lists tiny acts of refusal that accumulate into visible change.", censored = true },
  { title = "The Market Ledger", author = "Greta Olsen", synopsis = "A ledger of daily sales accompanied by quick, fond descriptions of customers.", censored = false },
  { title = "Catalog of Shared Histories", author = "Ibrahim Noor", synopsis = "A catalog aligns personal histories to reveal overlapping claims to place.", censored = true },
  { title = "Porchlight Stories", author = "Yara Haddad", synopsis = "Short anecdotes told under porchlights about neighbors and old jokes.", censored = false },
  { title = "Brief on Allocation", author = "Roland Phelps", synopsis = "A brief that quietly outlines how resources are allocated away from certain areas.", censored = true },
  { title = "The Little Bird Book", author = "Faye Donovan", synopsis = "A simple birdwatching log with tiny drawings and local names.", censored = false },
  { title = "Notes on Who Speaks", author = "Diego Alonso", synopsis = "Observations of public meetings showing who is heard first and why that order persists.", censored = true },
  { title = "Cupboard Inventory", author = "Nell Carter", synopsis = "A neat inventory of pantry items and the recipes that use them most.", censored = false },
  { title = "Manual of Quiet Organization", author = "Soren Beck", synopsis = "A manual that suggests organizing techniques which subtly change power balances.", censored = true },
  { title = "Evening Postcards", author = "Marta Flores", synopsis = "A set of short postcard-like notes exchanged between friends across a year.", censored = false },
  { title = "The Register of Small Claims", author = "Hana Kim", synopsis = "A register notes minor claims and how the system resolves them unevenly.", censored = true },
  { title = "Seed Packets", author = "Ollie Marsh", synopsis = "Packets of seeds labeled with planting tips and the gardeners who prefer them.", censored = false },
  { title = "A Note on the Commons", author = "Rory Blake", synopsis = "A short note arguing that small shared spaces change when certain rules are enforced.", censored = true },
  { title = "The Evening Ledger", author = "Fiona Park", synopsis = "A ledger kept by a caretaker listing daily incidents and small reconciliations.", censored = false },
  { title = "The Guide to Quiet Exits", author = "Markus Leclerc", synopsis = "A guide outlines ways people quietly remove themselves from obligations and what follows.", censored = true },
  { title = "Porch Plant Care", author = "Isla Romero", synopsis = "Simple care tips for porch plants and notes on who waters them most mornings.", censored = false },
  { title = "Index of Small Omissions", author = "Victor Ames", synopsis = "An index of omissions in reports that, read together, change the narrative of events.", censored = true },
  { title = "Handful of Rhymes", author = "June Carter", synopsis = "A slim collection of rhymes meant for quick recitation and neighborhood games.", censored = false },
  { title = "A Brief on Surveillance Habits", author = "Liam Fox", synopsis = "A brief that catalogs everyday watchfulness and the systems that formalize it.", censored = true },
  { title = "The Market Sketchbook", author = "Rhea Das", synopsis = "Sketches of stalls and the small gestures sellers use to greet regulars.", censored = false },
  { title = "Notes on Opening Hours", author = "Daniel Cho", synopsis = "A set of notes showing how opening hours privilege certain routines over others.", censored = true },
  { title = "Kitchen Corners", author = "Aya Nakamura", synopsis = "Short scenes set in kitchen corners where small decisions are made and shared.", censored = false },
  { title = "Annotations on Distribution", author = "Gregory Moss", synopsis = "Annotations in distribution lists reveal prioritization hidden in plain sight.", censored = true },
  { title = "Pocket Atlas of Benches", author = "Lina Garza", synopsis = "A tiny atlas pointing to favored benches and the people who occupy them.", censored = false },
  { title = "Minutes That Were Not Announced", author = "Hassan Karim", synopsis = "Unannounced minutes expose decisions taken before public discussion begins.", censored = true },
  { title = "Little Recipes for Rainy Days", author = "Beth Lowell", synopsis = "Recipes and suggestions for meals that comfort during long rainy afternoons.", censored = false },
  { title = "The Unmarked Map", author = "Orla Byrne", synopsis = "An unmarked map shows meeting places omitted from official guides and why they matter.", censored = true },
  { title = "The Florist's Ledger", author = "Milos Novak", synopsis = "A ledger of sales with small notes about ceremonies and the people who attend them.", censored = false },
  { title = "Guide to Quiet Enrollment", author = "Sofia Tal", synopsis = "A guide describing enrollment practices that quietly favor some applicants over others.", censored = true },
  { title = "The Pocket Songbook", author = "Rafi Bloom", synopsis = "A short songbook passed among friends for singalongs on long walks.", censored = false },
  { title = "The Index of Minor Exceptions", author = "June Parkes", synopsis = "An index listing exceptions that, when tallied, show systematic divergence from rules.", censored = true },
  { title = "Streetcorner Stories", author = "Kamilah Jones", synopsis = "Quick stories overheard at street corners about small moments of kindness.", censored = false },
  { title = "Notes on Reserved Seats", author = "Leonard Ames", synopsis = "Observations on who gets reserved seating and how those patterns persist unnoticed.", censored = true },
  { title = "A Little Guide to Compost", author = "Nadia Cook", synopsis = "Practical composting tips and a few short tales of neighborhood swaps.", censored = false },
  { title = "Manual of Soft Exclusion", author = "Owen Hartley", synopsis = "A manual that describes subtle practices of exclusion disguised as efficiency.", censored = true },
  { title = "The Pocket Calendar", author = "Mira Santos", synopsis = "A small calendar with notes about markets, moons, and annual traditions.", censored = false },
  { title = "Annotations from the Back Door", author = "Cyrus Bell", synopsis = "Short annotations about who uses the back door and what that reveals about access.", censored = true },
  { title = "Neighborhood Songlines", author = "Zara Malik", synopsis = "Short refrains that neighbors hum while walking familiar routes.", censored = false },
  { title = "Guide to Quiet Transfers", author = "Peter Liao", synopsis = "A concise guide describing how transfers of goods are routed away from scrutiny.", censored = true },
  { title = "The Little Seed Catalog", author = "Noelle Cruz", synopsis = "A seed catalog with small notes on which varieties thrive in certain yards.", censored = false },
  { title = "Register of Last Words", author = "Hannah Price", synopsis = "A register of final utterances in council hearings that hint at suppressed questions.", censored = true },
  { title = "The Market's Brief Tales", author = "Evan Wright", synopsis = "Short tales told between stalls about the year's odd events and small recoveries.", censored = false },
  { title = "Notes on Access Codes", author = "Marta Silva", synopsis = "Notes about codes and keys that determine who can enter certain spaces.", censored = true },
  { title = "Lilac Evenings", author = "Jon Perez", synopsis = "A brief collection of evenings spent beneath lilac bushes and quiet exchanges.", censored = false },
  { title = "A Short Handbook of Redirection", author = "Clara Voss", synopsis = "A handbook showing how requests are redirected and which communities are marginalized.", censored = true },
  { title = "Small Tales of the Bus Stop", author = "Diego Flores", synopsis = "A string of small tales overheard at the bus stop over a single week.", censored = false },
  { title = "Index of Forgotten Services", author = "Rosa Jimenez", synopsis = "An index documenting services that were cut and the populations that suffered most.", censored = true },
  { title = "Pocket Instructions for Tea", author = "Liam O'Connell", synopsis = "Short instructions for brewing tea the local way and the stories tied to each cup.", censored = false }
}
